spring.application.name=gestaoFinanceira

# Banco
spring.datasource.url=jdbc:postgresql://db.jbmsafnimcwscvjfcbhh.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=MendzDev2026

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Pool de conexões
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# Segurança JWT (Chave secreta para assinatura dos tokens)
api.security.token.secret=U3VwZXJTZWNyZXRLa2trQFRlc3RlMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=